blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import PostCreateView, PostListView, PostDetailView, PostUpdateView, PostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create', PostCreateView.as_view(), name='create'),
    path('', PostListView.as_view(), name='list'),
    path('view/<int:pk>/', PostDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', PostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'null': 'True', 'blank': 'True'}


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name='название поста')
    slug = models.CharField(max_length=200, verbose_name='slug')
    content = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='превью', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import render
from django.urls import reverse_lazy, reverse

from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from pytils.translit import slugify

import blog
from blog.models import Post


# Create your views here.


class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Post
    fields = ('title', 'content', 'preview', 'is_published')
    success_url = reverse_lazy('blog:list')
    permission_required = 'blog.add_post'

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()

        return super().form_valid(form)


class PostListView(LoginRequiredMixin, ListView):
    model = Post

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Post
    fields = ('title', 'content', 'preview')
    permission_required = 'blog.change_post'

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()

        return super().form_valid(form)


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        if self.object.views_count == 10:
            send_mail('Ура!!!', 'У тебя 100 просмотров', '79117241625@yandex.ru', ['79117241625@yandex.ru'], fail_silently=False)
        self.object.save()
        return self.object


class PostDeleteView(PermissionRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:list')
    permission_required = 'blog.delete_post'

blog/templates/blog/post_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить пост "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Да</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-warning">Передумал</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ object.title }}</h3>
                    <h5><small class="text-body-secondary">{{ object.slug }}</small></h5>
                </div>
                <div class="card-body">
                    <img src="{{ object.preview|mediapath }}" class="img-fluid rounded-start"
                         alt="Изображение отсутствует">
                    <p>
                        {{ object.content }}
                    </p>
                    <a href="{% url 'blog:edit' object.pk %}" type="button"
                       class="btn btn-primary btn-sm">Редактировать</a>
                    <a href="{% url 'blog:delete' object.pk %}" type="button" class="btn btn-primary btn-sm">Удалить</a>
                </div>
                <div class="card-footer">
                    Просмотры: {{ object.views_count }}
                    <p class="card-text"><small class="text-muted">Создан {{ object.created_at }}</small></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить пост</a>
</div>
<div class="row text-center">
    {% for object in object_list %}
    <div class="col-12">
        <div class="card mb-3" style="max-width: 50 px;">
            <div class="row g-0">

                <div class="card-header">
                    <h3 class="card-title">{{ object.title }}</h3>
                    <h5><small class="text-body-secondary">{{ object.slug }}</small></h5>
                </div>

                <div class="card-body">
                    <img src="/media/{{ object.preview }}" class="img-fluid rounded-start"
                         alt="Изображение отсутствует">
                    <p>
                        {{ object.content|slice:"0:100" }}
                    </p>
                    <div class="row">
                        <div class="d-grid gap-2 d-md-block">
                            <a href="{% url 'blog:view' object.pk %}" type="button" class="btn btn-primary btn-sm">Читать
                                полностью</a>
                            <a href="{% url 'blog:edit' object.pk %}" type="button" class="btn btn-primary btn-sm">Редактировать</a>
                            <a href="{% url 'blog:delete' object.pk %}" type="button" class="btn btn-primary btn-sm">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}