blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import PostCreateView, PostListView, PostDetailView, PostUpdateView, PostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create', PostCreateView.as_view(), name='create'),
    path('', PostListView.as_view(), name='list'),
    path('view/<int:pk>/', PostDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', PostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, toggle_publish, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('create/', ProductCreateView.as_view(), name='create'),
    path('', ProductListView.as_view(), name='list'),
    path('contacts/', contacts, name='contacts'),
    path('view/<int:pk>/catalog/', cache_page(60)(ProductDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('publish/<int:pk>/', toggle_publish, name='toggle_publish'),
    path('categories/', CategoryListView.as_view(), name='categories'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name='наименование')
    description = models.TextField(blank=True, null=True, verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='название')
    description = models.TextField(null=True, blank=True, verbose_name='описание')
    preview = models.ImageField(upload_to='products/', null=True, blank=True, verbose_name='изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена за покупку')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='дата изменения')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец')
    is_published = models.BooleanField(default=False, verbose_name='Опубликован')

    def __str__(self):
        return f'{self.name} {self.category} {self.price} '

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['name', 'price']
        permissions = [
            ("can_cancel_publish", "Can cancel publish"),
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт', related_name='versions')
    version_number = models.PositiveIntegerField(default=0, verbose_name='номер версии')
    title = models.CharField(max_length=250, verbose_name='название версии')
    is_active = models.BooleanField(default=True, verbose_name='активная версия')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.forms.fields import BooleanField

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        # fields = '__all__'
        # fields = ('name', 'description', 'preview', 'category', 'price',)
        exclude = ('owner',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        for word in self.forbidden_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f'Название продукта не может содержать: {self.forbidden_words}!')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        for word in self.forbidden_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f'Описание продукта не может содержать: {self.forbidden_words}!')

        return cleaned_data


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        # fields = '__all__'
        fields = ('description', 'category', 'is_published',)
        # exclude = ('owner',)


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'


VersionFormset = inlineformset_factory(Product, Version, VersionForm, extra=1)

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Subquery, OuterRef
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView

from catalog.forms import ProductForm, VersionForm, VersionFormset, ProductModeratorForm
from catalog.models import Product, Version, Category
from catalog.services import get_cached_categories


class ProductCreateView(LoginRequiredMixin, CreateView):
    """
    Класс для создания продукта
    """
    model = Product
    # fields = ('name', 'description', 'preview', 'category', 'price')
    form_class = ProductForm
    success_url = reverse_lazy('catalog:list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.method == "POST":
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save(commit=False)
            self.object.owner = self.request.user
            self.object.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


class ProductListView(ListView):
    """
    Класс для отображения списка продуктов
    """
    model = Product

    def get_context_data(self,*args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        products = Product.objects.all()

        for product in products:
            versions = Version.objects.filter(product=product)
            active_versions = versions.filter(is_active=True)
            if active_versions:
                product.active_version = active_versions.last().version_number
            else:
                product.active_version = '-'
        context_data['object_list'] = products
        return context_data


def contacts(request):
    if request.method == "POST":
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'You have new message from {name}({phone}): {message}')

    context = {'title': 'Контакты'}
    return render(request, 'catalog/contacts.html', context)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    """
    класс для редактирования Продукта
    """
    model = Product
    form_class = ProductForm
    # permission_required = "catalog.change_product"
    # success_url = reverse_lazy('catalog:detail')

    def get_success_url(self, *args, **kwargs):
        return reverse('catalog:edit', args=[self.get_object().pk])

    def test_func(self):
        """
        Проверка пользователя, является ли владельцем продукта или модератором
        """
        user = self.request.user
        author = self.get_object().owner
        return user == author or user.groups.filter(name='moderator').exists()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        if self.request.method == "POST":
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if form.is_valid() and formset.is_valid():
            self.object = form.save(commit=False)
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm('catalog.can_cancel_publish'):
            return ProductModeratorForm
        raise PermissionDenied


@login_required
def toggle_publish(request, pk):
    product_item = get_object_or_404(Product, pk=pk)
    if request.user.has_perm('catalog.can_cancel_publish') or request.get_object().owner:
        if product_item.is_published:
            product_item.is_published = False
        else:
            product_item.is_published = True
        product_item.save()

        return redirect(reverse('catalog:list'))


class ProductDetailView(LoginRequiredMixin, DetailView):
    """
    Класс для просмотра Продукта
    """
    model = Product


# def product(request, pk):
#     product_item = Product.objects.get(pk=pk)
#     context = {
#         'object_list': Product.objects.filter(id=pk),
#         'title': f'Вы выбрали {product_item.name}'
#     }
#     return render(request, 'catalog/product.html', context)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    """
    Класс для удаления Продукта
    """
    model = Product
    success_url = reverse_lazy('catalog:list')


class CategoryListView(ListView):
    """
    Класс для отображения списка продуктов
    """
    model = Category
    template_name = 'catalog/category_list.html'

    # def get_context_data(self, *args, **kwargs):
    #     context_data = super().get_context_data(*args, **kwargs)
    #     context_data['object_list'] = get_cached_categories
    #     return context_data

    def get_queryset(self):
        return get_cached_categories()

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>{{ title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/pricing/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->

    <script type="text/javascript"
            src="https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=mwwCNUlsjI0jK2Q5VeJtbB-oqHQ76uz0PUKrg4Y6tBixmFvizLsr-Gl4JrH9QDYwmdapd0lmFfGZhHN4eoLXPyIqfWWJZbe-7iR_WX9X4O4"
            charset="UTF-8"></script>
</head>

<body>
{% include 'catalog/includes/inc_main_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

{% block content%}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            <img class="mb-2" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt=""
                 width="24" height="24">
            <small class="d-block mb-3 text-muted">&copy; 2017-2018</small>
        </div>
        <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Cool stuff</a></li>
                <li><a class="text-muted" href="#">Random feature</a></li>
                <li><a class="text-muted" href="#">Team feature</a></li>
                <li><a class="text-muted" href="#">Stuff for developers</a></li>
                <li><a class="text-muted" href="#">Another one</a></li>
                <li><a class="text-muted" href="#">Last time</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Resource</a></li>
                <li><a class="text-muted" href="#">Resource name</a></li>
                <li><a class="text-muted" href="#">Another resource</a></li>
                <li><a class="text-muted" href="#">Final resource</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Team</a></li>
                <li><a class="text-muted" href="#">Locations</a></li>
                <li><a class="text-muted" href="#">Privacy</a></li>
                <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
<script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });




</script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% block content %}


<div class="container">
    <h5 class="card-title">Категории:</h5>
    {% for object in object_list %}
    <ul>
        <h5 class="card-title">{{ object.name | title }}</h5>
        <!--         <p class="card-text">{{ object.description|slice:"0:100" }}</p>-->
    </ul>
    {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-6 col-md-4 col-sm-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>Россия</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>г. Санкт-Петербург</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                       required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                       placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Сообщение" required></textarea>
                            </div>

                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary form-control">Отправить
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}


<div class="container">

    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card-deck mb-3 text-center">
                <div class="card" style="width: 18rem;">
                    <img src="{{ object.preview|mediapath }}" class="img-fluid rounded-start"
                         alt="Изображение отсутствует">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.name | title }}</h5>
                        <p class="card-text">{{ object.description|slice:"0:100" }}</p>
                        <h5 class="card-title">{{ object.price }} РУБ.</h5>
                        <a href="{% url 'catalog:product_detail' object.pk %}" class="btn btn-primary">Подробнее</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="container">
    <div class="row">
        {% for object in object_list %}
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{ object.preview|mediapath }}" class="img-fluid rounded-start" alt="Изображение отсутствует">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ object.name | title }}</h5>
                            <p class="card-text">{{ object.description }}</p>
                            <h5 class="card-title">{{ object.price }} РУБ.</h5>
                            <p class="card-text"><small class="text-body-secondary">Создан {{ object.created_at }}</small></p>
                            <p class="card-text"><small class="text-body-secondary">Изменен {{ object.updated_at }}</small></p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% endblock %}
</div>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Да</button>
                        <a href="{% url 'catalog:list' %}" class="btn btn-warning">Передумал</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="container">
    <div class="row">
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ object.preview|mediapath }}" class="img-fluid rounded-start"
                         alt="Изображение отсутствует">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.name | title }}</h5>
                        <p class="card-text">Категория: {{ object.category | title }}</p>
                        <p class="card-text">{{ object.description }}</p>
                        <h5 class="card-title">{{ object.price }} РУБ.</h5>
                        <p class="card-text"><small class="text-body-secondary">Создан {{ object.created_at }}</small>
                        </p>
                        <p class="card-text"><small class="text-body-secondary">Изменен {{ object.updated_at }}</small>
                        </p>
                    </div>
<!--                    {% if user.is_authenticated %}-->
                    {% if perms.catalog.change_product or user == product.owner %}
                    <div class="card-footer">
                        <a href="{% url 'catalog:edit' object.pk %}" type="button" class="btn btn-primary btn-sm">
                            Изменить
                        </a>
                        {% endif %}
                        {% if perms.catalog.delete_product %}
                        <a href="{% url 'catalog:delete' object.pk %}" type="button" class="btn btn-primary btn-sm">
                            Удалить
                        </a>
                        {% endif %}
                    </div>
<!--                    {% endif %}-->
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</div>

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <form class='row' method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                {% if object %}
                    <p class="card_text">Редактирование продукта</p>
                {% else %}
                    <p class="card_text">Создание продукта</p>
                {% endif %}
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-success">
                    {% if object %}
                        Сохранить
                    {% else %}
                        Создать
                    {% endif %}
                </button>
                {% if object %}
                    {% if object.is_published %}
                      <a class="btn btn-primary p-2" href="{% url 'catalog:toggle_publish' object.pk %}">Снять с публикации</a>
                    {% else %}
                      <a class="btn btn-primary p-2" href="{% url 'catalog:toggle_publish' object.pk %}">Опубликовать</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <p class="card_text">Версии</p>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                    {% endfor %}
                </div>

            </div>
        </div>

    </form>
</div>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
<div class="col-12 mb-5">
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'catalog:create' %}">Добавить продукт в Авоську</a>
    {% endif %}
</div>
<div class="container">

    <div class="row">
        {% for object in object_list %}
        {% if object.is_published %}
        <div class="col-md-4">
            <div class="card-deck mb-3 text-center">
                <div class="card" style="width: 18rem;">
                    <img src="{{ object.preview|mediapath }}" class="img-fluid rounded-start"
                         alt="Изображение отсутствует">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.name | title }}</h5>
                        <p class="card-text">{{ object.description|slice:"0:100" }}</p>
                        <h5 class="card-title">{{ object.price }} РУБ.</h5>
                        <p class="card-text">Версия: {{ object.active_version }}</p>
                        <a href="{% url 'catalog:view' object.pk %}" class="btn btn-primary">Подробнее</a>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% endblock %}
</div>